<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Mailmaster gestion de mail">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Cloudmails</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
    <main>
      <header class="box txtcenter site-hero">
        <picture class="site-logo"><?php echo file_get_contents('../public/img/logo.svg') ?></picture>
        <h1 class="site-tagline">Créer un compte mail gratuit et sécurisé</h1>
      </header>
      <div class="flex-center">
        <div class="form-newmail">
          <form>
            <p>
              <div>
                <label for="newUserMail">Mail <span class="color--success js-newUserDebug"></span></label>
              </div>
                <input class="js-inputMail" type="text" name="newUserMail" id="newUserMail">
                @cloudmails.eu
            </p>
            <p>
              <div>
                <label for="newUserPassword">Mot de passe</label>
              </div>
              <input class="js-inputMailPass" type="password" name="newUserPassword" id="newUserPassword">
            </p>
            <p>
              <input class="btn btn--primary js-mailSubmit" disabled="disabled" type="submit" name="portalsubmit" id="newUserSubmit" value="Créer mon adresse mail">
            </p>
          </form>
        </div>
      </div>
    </main>
  </div>
  <footer class="site-footer">
    <?php require_once('footer.phtml') ?>
  </footer>
  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
