<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Mailmaster gestion de mail">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Cloudmails</title>
	<link rel="stylesheet" href="css/style.css">
</head>
<body>
  <div class="place-center">
    <main>
      <header class="box txtcenter site-hero">
        <picture class="site-logo"><?php echo file_get_contents('../public/img/logo.svg') ?></picture>
        <p class="h1-like"><strong>Cloudmails.eu</strong></p>
        <h1 class="site-tagline">Adresse mail gratuite et sécurisé</h1>
      </header>
      <div class="flex-center">
        <div class="form-newmail">
          <form>
            <div class="mbm">
              <h2 class="form-newmail__title">Créer son adresse mail</h2>
              <p><small>(Tous les champs doivent être remplis)</small></p>
            </div>
            <div class="mbm">
              <div class="form-newmail__input-group">
                <label class="form-newmail__label" for="newUserMail">Mail <span class="color--success js-newUserDebug"></span></label>
                <input class="form-newmail__input js-inputMail" type="text" name="newUserMail" id="newUserMail" maxlength="50" autofocus="">
                <span class="form-newmail__domain">@cloudmails.eu</span>
              </div>
              <div class="form-newmail__input-group">
                <label class="form-newmail__label" for="newUserPassword">Mot de passe</label>
                <input class="form-newmail__input js-inputMailPass" type="password" name="newUserPassword" id="newUserPassword">
              </div>
            </div>
            <div>
              <input class="btn btn--ghost form-newmail__submit js-mailSubmit" disabled="disabled" type="submit" name="portalsubmit" id="newUserSubmit" value="Créer mon adresse mail">
            </div>
          </form>
        </div>
      </div>
    </main>
  </div>
  <footer class="site-footer">
    <?php require_once('footer.phtml') ?>
  </footer>
  <script type="text/javascript" src="js/script.js"></script>
</body>
</html>
